# <font color= 'aqua'> Practice: </font>

In [172]:
#Mount CSV file in drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [173]:
import pandas as pd
import numpy as np
from word2number import w2n
import matplotlib.pyplot as plt
from sklearn import linear_model

In [174]:
#Reading Data
homePrices = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Csv_file/homeprices.csv')
homePrices.keys()

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [175]:
homePricesDf = pd.DataFrame(homePrices)
print(homePricesDf)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [176]:
homePricesDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int64
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64
 3   price     6 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes

In [177]:
homePricesDf.describe()

              area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [178]:
homePricesDf.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [179]:
homePricesDf['bedrooms'] = np.floor(
    homePricesDf['bedrooms'].fillna(homePricesDf['bedrooms'].median())
)
print(homePricesDf)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [180]:
reg = linear_model.LinearRegression()
reg.fit(homePricesDf.drop(columns= ['price']), homePricesDf.price)

LinearRegression()

In [181]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [182]:
reg.intercept_

np.float64(221323.00186540396)

In [183]:
reg.predict(pd.DataFrame({
    'area': [3200, 2500],
    'bedrooms': [4, 4],
    'age': [18, 5]
}))

array([615307.4140366 , 578876.03748933])

# <font color= 'aqua'> Exercise: </font>

In [184]:
hiring = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Csv_file/hiring.csv')
hiring.columns = ['experience', 'test_score', 'interview_score', 'salary']
hiring.keys()

Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

In [185]:
hiringDf = pd.DataFrame(hiring)
print(hiringDf)

  experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [186]:
hiringDf.isnull().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [187]:
hiringDf['experience'] = hiringDf['experience'].fillna("Zero")
hiringDf['experience'] = hiringDf['experience'].apply(
    w2n.word_to_num
)

hiringDf['test_score'] = np.floor(
    hiringDf['test_score'].fillna(hiringDf['test_score'].median())
)

print(hiringDf)

   experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [188]:
reg = linear_model.LinearRegression()
reg.fit(hiringDf.drop(columns= ['salary']), hiringDf['salary'])

LinearRegression()

In [189]:
salPredict= reg.predict(pd.DataFrame({
    'experience': [2, 12],
    'test_score': [9, 10],
    'interview_score': [6, 10]
}))

print(np.round(salPredict))

[53206. 92002.]