# <font color="Blue">**Assignment:**</font>
#### *Generating a dataset and demonstrate various data pre-processing techniques listed bellow*
- Reshaping the data
- Filtering the data
- Merging the data
- Handling missing values
- Feature Normalization (Min-Max normalization)

<font color="turquoise"><h3>Generating dataset</h3>

In [133]:
#Importing modules
import numpy as np
import pandas as pd

In [134]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Amit", "Riya", "John", "Sara", "Karan", "Meena", "Arjun", "Nisha"],
    "age": [20, 21, 19, np.nan, 22, 20, 23, 21],
    "math_score": [85, 90, np.nan, 88, 76, 95, 89, 92],
    "science_score": [78, np.nan, 80, 85, 70, 96, 88, np.nan],
    "city": ["Kolkata", "Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai", "Delhi", "Kolkata"]
})

students

   student_id   name   age  math_score  science_score     city
0         101   Amit  20.0        85.0           78.0  Kolkata
1         102   Riya  21.0        90.0            NaN    Delhi
2         103   John  19.0         NaN           80.0   Mumbai
3         104   Sara   NaN        88.0           85.0    Delhi
4         105  Karan  22.0        76.0           70.0  Kolkata
5         106  Meena  20.0        95.0           96.0   Mumbai
6         107  Arjun  23.0        89.0           88.0    Delhi
7         108  Nisha  21.0        92.0            NaN  Kolkata

In [135]:
attendance = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 109],
    "attendance_percentage": [92, 85, 88, 90, np.nan, 95, 95, 75]
})

attendance

   student_id  attendance_percentage
0         101                   92.0
1         102                   85.0
2         103                   88.0
3         104                   90.0
4         105                    NaN
5         106                   95.0
6         107                   95.0
7         109                   75.0

<font color= "skyblue"><h3>1. Reshaping the data</h3>

In [136]:
#creating a array with toal score from the student table
score = np.array(students[["math_score", "science_score"]])

print("Original shape: ", score.shape)
#Reshaping the data
score_reshaped = score.reshape(16, 1)
print("Reshaped data: ", score_reshaped.shape)

Original shape:  (8, 2)
Reshaped data:  (16, 1)

<font color= 'skyblue'><h3>2. Filtering the data</h3>

In [137]:
#Filtering on single condition
single_filtered_df = students[students['city'] == 'Delhi']
print("Students from delhi: \n")
print(single_filtered_df[['student_id', 'name', 'city']])
print("\n")

#filtering on multiple condition
multi_filtered_df = students[
    (students['city'] == 'Delhi') &
    (students['age'] > 20)]

print("Students from delhi and age avobe 20: \n")
print(multi_filtered_df[['student_id', 'name', 'city', 'age']])

Students from delhi:

   student_id   name   city
1         102   Riya  Delhi
3         104   Sara  Delhi
6         107  Arjun  Delhi


Students from delhi and age avobe 20:

   student_id   name   city   age
1         102   Riya  Delhi  21.0
6         107  Arjun  Delhi  23.0

<font color= 'skyblue'><h3>3. Merging the data</h3>

In [138]:
#Merging student table and attendance table
mrg_df = pd.merge(students, attendance, on='student_id', how='inner')

print("Merged data: \n")
print(mrg_df[['student_id', 'name', 'attendance_percentage']])

Merged data:

   student_id   name  attendance_percentage
0         101   Amit                   92.0
1         102   Riya                   85.0
2         103   John                   88.0
3         104   Sara                   90.0
4         105  Karan                    NaN
5         106  Meena                   95.0
6         107  Arjun                   95.0

<font color= 'skyblue'><h3>4. Handling missing values</h3>

In [139]:
#Unhandled missing values
print("Raw data: \n")
print(students)
print("\n")

#Handling missing values
students["age"]= students["age"].fillna(
    students["age"].mean())
students["math_score"]= students["math_score"].fillna(
    students["math_score"].mean())
students["science_score"]= students["science_score"].fillna(
    students["science_score"].mean())

print("Processed data: \n")
print(students)

Raw data:

   student_id   name   age  math_score  science_score     city
0         101   Amit  20.0        85.0           78.0  Kolkata
1         102   Riya  21.0        90.0            NaN    Delhi
2         103   John  19.0         NaN           80.0   Mumbai
3         104   Sara   NaN        88.0           85.0    Delhi
4         105  Karan  22.0        76.0           70.0  Kolkata
5         106  Meena  20.0        95.0           96.0   Mumbai
6         107  Arjun  23.0        89.0           88.0    Delhi
7         108  Nisha  21.0        92.0            NaN  Kolkata


Processed data:

   student_id   name        age  math_score  science_score     city
0         101   Amit  20.000000   85.000000      78.000000  Kolkata
1         102   Riya  21.000000   90.000000      82.833333    Delhi
2         103   John  19.000000   87.857143      80.000000   Mumbai
3         104   Sara  20.857143   88.000000      85.000000    Delhi
4         105  Karan  22.000000   76.000000      70.000000  Kolkata
5         106  Meena  20.000000   95.000000      96.000000   Mumbai
6         107  Arjun  23.000000   89.000000      88.000000    Delhi
7         108  Nisha  21.000000   92.000000      82.833333  Kolkata

<font color= 'skyblue'><h3>5. Feature Normalization (Min-Max normalization)</h3>

In [140]:
print("Feature Normalization: \n")
norm_df = students.copy()
col= norm_df["math_score"]

norm_df['math_score_norm']= (col - col.min()) / (col.max() - col.min())
print(norm_df)

Feature Normalization:

   student_id   name        age  math_score  science_score     city  \
0         101   Amit  20.000000   85.000000      78.000000  Kolkata
1         102   Riya  21.000000   90.000000      82.833333    Delhi
2         103   John  19.000000   87.857143      80.000000   Mumbai
3         104   Sara  20.857143   88.000000      85.000000    Delhi
4         105  Karan  22.000000   76.000000      70.000000  Kolkata
5         106  Meena  20.000000   95.000000      96.000000   Mumbai
6         107  Arjun  23.000000   89.000000      88.000000    Delhi
7         108  Nisha  21.000000   92.000000      82.833333  Kolkata

   math_score_norm
0         0.473684
1         0.736842
2         0.624060
3         0.631579
4         0.000000
5         1.000000
6         0.684211
7         0.842105